"""Repository ports (Protocols) for the catalog bounded context.

Routers depend on these, never on SQLAlchemy. A future external adapter
(ServiceNow, LeanIX, Jira) implements the same Protocol; read-only sources
set read_only=True and the HTTP layer answers writes with 405."""
from __future__ import annotations

from typing import Protocol

from app.catalog.domain import (
    Art,
    Criticality,
    DependencyType,
    LifecycleState,
    Product,
    Service,
    ServiceDependency,
)


class ArtRepository(Protocol):
    @property
    def read_only(self) -> bool: ...
    def list(self) -> list[Art]: ...
    def get(self, art_id: int) -> Art: ...
    def create(self, *, name: str, description: str | None = None) -> Art: ...
    def update(self, art_id: int, changes: dict) -> Art: ...
    def delete(self, art_id: int) -> None: ...


class ProductRepository(Protocol):
    @property
    def read_only(self) -> bool: ...
    def list(self) -> list[Product]: ...
    def get(self, product_id: int) -> Product: ...
    def create(self, *, name: str, art_id: int, description: str | None = None,
               team_id: int | None = None) -> Product: ...
    def update(self, product_id: int, changes: dict) -> Product: ...
    def delete(self, product_id: int) -> None: ...


class ServiceRepository(Protocol):
    @property
    def read_only(self) -> bool: ...
    def get(self, service_id: int) -> Service: ...
    def tree(self, product_id: int) -> list[Service]: ...
    def list_all(self) -> list[Service]: ...
    def create(self, *, name: str, product_id: int, description: str | None = None,
               parent_service_id: int | None = None, owner_user_id: int | None = None,
               lifecycle_state: LifecycleState = LifecycleState.PLANNED) -> Service: ...
    def update(self, service_id: int, changes: dict) -> Service: ...
    def delete(self, service_id: int) -> None: ...
    def list_dependencies(
        self, service_id: int
    ) -> tuple[list[ServiceDependency], list[ServiceDependency]]: ...
    def add_dependency(self, *, from_service_id: int, to_service_id: int,
                       dep_type: DependencyType, criticality: Criticality,
                       note: str | None = None) -> ServiceDependency: ...
    def remove_dependency(self, from_service_id: int, dep_id: int) -> None: ...
